# Generated by Django 3.2.14 on 2022-08-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='gallery')),
                ('desc', models.TextField()),
                ('price', models.IntegerField(max_length=250)),
            ],
        ),
    ]
